### ISSUE TITLE
ROS2 Application

### ISSUE THREAD

**Issue by guilyx** [master-coro/rtros-management#31]
- [ ] choose an example package
- [ ] observe metrics for Xenomai+ROS2 || No Xenomai 
- [ ] build a "homemade" package

**Comment by guilyx** [comment]
https://github.com/ros2-realtime-demo/pendulum/blob/eloquent/docs/real_time_tutorial.md

**Comment by guilyx** [comment]
```
---
timer_stats:
  timer_count: 173493
  jitter_mean_usec: 0.017394836649528584
  jitter_min_usec: -553.807
  jitter_max_usec: 1546.873
  jitter_std_usec: 18.48878661343171
sensor_stats:
  msg_count: 173493
  deadline_misses_count: 0
command_stats:
  msg_count: 173493
  deadline_misses_count: 0
setpoint_stats:
  msg_count: 0
  deadline_misses_count: 0
rusage_stats:
  max_resident_set_size: 44500
  total_minor_pagefaults: 2810
  total_major_pagefaults: 0
  minor_pagefaults_active_node: 98
  major_pagefaults_active_node: 0
  voluntary_context_switches: 946109
  involuntary_context_switches: 1121
---

```
